# --- CONSTANTES DE LA VENTANA ---
WINDOW_TITLE = "Minecraft Launcher"
WINDOW_WIDTH = 600
WINDOW_HEIGHT = 900

# --- CONSTANTES DE RUTA ---
DATA_FILE = "data/app_data.json"

# --- CONSTANTES DE ESTILOS ---
BG_BLACK = "#4f4f4f"
BG_SECTION = "#383838"
TXT_WHITE = "#a9a9a9"
BORDER_BLACK = "#141414"
BORDER_WHITE = "#696969"

# --- CONSTANTES ---
VERSION_LAUNCHER = "0.1"